### ISSUE TITLE
Need user feedback when submitting data to Cesium ion for processing

### ISSUE THREAD

**Issue by gbeatty** [AnalyticalGraphicsInc/cesium-ion-webodm-plugin#8]
Depending on the size of the task being submitted, the Cesium ion upload process can take some time. During this time there isn't any indication to the user that anything is happening. The submission UI just stays up leaving the user wondering what's going on.

**Comment by ProjectBarks** [comment]
![2019-07-15 09 36 52](https://user-images.githubusercontent.com/4194371/61220539-84aa0500-a6e4-11e9-8cab-4b881937ee32.gif)

**Comment by ProjectBarks** [comment]
@gbeatty we are actually retiring this repo since we have been merged into [WebODM](https://github.com/OpenDroneMap/WebODM/tree/master/plugins).

I posted a screenshot of the current upload dialog. I think that adequately addresses everything you mentioned. If not feel free to give further feedback.
